# Generated by Django 3.2.8 on 2021-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=25)),
                ('fault', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('error_message', models.CharField(max_length=250)),
            ],
        ),
    ]
