# Generated by Django 3.2.8 on 2021-11-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_booksrequests_booksrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrequest',
            name='fault',
        ),
    ]
