# Generated by Django 3.2.8 on 2021-11-11 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_booksrequest_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrequest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
