# Generated by Django 3.2.8 on 2021-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_booksrequest_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
