# Generated by Django 3.2.8 on 2021-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='revisionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=10)),
                ('releasedate', models.DateField(auto_now_add=True)),
                ('shortdescription', models.CharField(max_length=50)),
                ('fulldescription', models.TextField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
