# Generated by Django 3.2.8 on 2021-11-11 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionhistory',
            name='releasedate',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
